- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
   ssl_verify: "False"
  tasks:
  - name: Configure shaping policies.
    fortios_firewall_shaping_policy:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      state: "present"
      firewall_shaping_policy:
        app_category:
         -
            id:  "4"
        app_group:
         -
            name: "default_name_6 (source application.group.name)"
        application:
         -
            id:  "8"
        class_id: "9"
        comment: "Comments."
        diffserv_forward: "enable"
        diffserv_reverse: "enable"
        diffservcode_forward: "<your_own_value>"
        diffservcode_rev: "<your_own_value>"
        dstaddr:
         -
            name: "default_name_16 (source firewall.address.name firewall.addrgrp.name)"
        dstaddr6:
         -
            name: "default_name_18 (source firewall.address6.name firewall.addrgrp6.name)"
        dstintf:
         -
            name: "default_name_20 (source system.interface.name system.zone.name)"
        groups:
         -
            name: "default_name_22 (source user.group.name)"
        id:  "23"
        internet_service: "enable"
        internet_service_custom:
         -
            name: "default_name_26 (source firewall.internet-service-custom.name)"
        internet_service_custom_group:
         -
            name: "default_name_28 (source firewall.internet-service-custom-group.name)"
        internet_service_group:
         -
            name: "default_name_30 (source firewall.internet-service-group.name)"
        internet_service_id:
         -
            id:  "32 (source firewall.internet-service.id)"
        internet_service_src: "enable"
        internet_service_src_custom:
         -
            name: "default_name_35 (source firewall.internet-service-custom.name)"
        internet_service_src_custom_group:
         -
            name: "default_name_37 (source firewall.internet-service-custom-group.name)"
        internet_service_src_group:
         -
            name: "default_name_39 (source firewall.internet-service-group.name)"
        internet_service_src_id:
         -
            id:  "41 (source firewall.internet-service.id)"
        ip_version: "4"
        name: "default_name_43"
        per_ip_shaper: "<your_own_value> (source firewall.shaper.per-ip-shaper.name)"
        schedule: "<your_own_value> (source firewall.schedule.onetime.name firewall.schedule.recurring.name firewall.schedule.group.name)"
        service:
         -
            name: "default_name_47 (source firewall.service.custom.name firewall.service.group.name)"
        srcaddr:
         -
            name: "default_name_49 (source firewall.address.name firewall.addrgrp.name)"
        srcaddr6:
         -
            name: "default_name_51 (source firewall.address6.name firewall.addrgrp6.name)"
        srcintf:
         -
            name: "default_name_53 (source system.interface.name system.zone.name)"
        status: "enable"
        tos: "<your_own_value>"
        tos_mask: "<your_own_value>"
        tos_negate: "enable"
        traffic_shaper: "<your_own_value> (source firewall.shaper.traffic-shaper.name)"
        traffic_shaper_reverse: "<your_own_value> (source firewall.shaper.traffic-shaper.name)"
        url_category:
         -
            id:  "61"
        users:
         -
            name: "default_name_63 (source user.local.name)"
