# Copyright 2019 Fortinet, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Ansible.  If not, see <https://www.gnu.org/licenses/>.

# Make coding more python3-ish
from __future__ import (absolute_import, division, print_function)
__metaclass__ = type

import os
import json
import pytest
from mock import ANY
from ansible.module_utils.network.fortios.fortios import FortiOSHandler

try:
    from ansible.modules.network.fortios import fortios_firewall_policy
except ImportError:
    pytest.skip("Could not load required modules for testing", allow_module_level=True)


@pytest.fixture(autouse=True)
def connection_mock(mocker):
    connection_class_mock = mocker.patch('ansible.modules.network.fortios.fortios_firewall_policy.Connection')
    return connection_class_mock


fos_instance = FortiOSHandler(connection_mock)


def test_firewall_policy_creation(mocker):
    schema_method_mock = mocker.patch('ansible.module_utils.network.fortios.fortios.FortiOSHandler.schema')

    set_method_result = {'status': 'success', 'http_method': 'POST', 'http_status': 200}
    set_method_mock = mocker.patch('ansible.module_utils.network.fortios.fortios.FortiOSHandler.set', return_value=set_method_result)

    input_data = {
        'username': 'admin',
        'state': 'present',
        'firewall_policy': {
            'action': 'accept',
            'anti_replay': 'enable',
            'application_list': 'test_value_5',
            'auth_cert': 'test_value_6',
            'auth_path': 'enable',
            'auth_redirect_addr': 'test_value_8',
            'av_profile': 'test_value_9',
            'block_notification': 'enable',
            'captive_portal_exempt': 'enable',
            'capture_packet': 'enable',
            'cifs_profile': 'test_value_13',
            'comments': 'test_value_14',
            'delay_tcp_npu_session': 'enable',
            'diffserv_forward': 'enable',
            'diffserv_reverse': 'enable',
            'diffservcode_forward': 'test_value_18',
            'diffservcode_rev': 'test_value_19',
            'disclaimer': 'enable',
            'dlp_sensor': 'test_value_21',
            'dnsfilter_profile': 'test_value_22',
            'dsri': 'enable',
            'dstaddr_negate': 'enable',
            'email_collect': 'enable',
            'emailfilter_profile': 'test_value_26',
            'firewall_session_dirty': 'check-all',
            'fixedport': 'enable',
            'fsso': 'enable',
            'fsso_agent_for_ntlm': 'test_value_30',
            'geoip_anycast': 'enable',
            'global_label': 'test_value_32',
            'http_policy_redirect': 'enable',
            'icap_profile': 'test_value_34',
            'identity_based_route': 'test_value_35',
            'inbound': 'enable',
            'inspection_mode': 'proxy',
            'internet_service': 'enable',
            'internet_service_negate': 'enable',
            'internet_service_src': 'enable',
            'internet_service_src_negate': 'enable',
            'ippool': 'enable',
            'ips_sensor': 'test_value_43',
            'label': 'test_value_44',
            'logtraffic': 'all',
            'logtraffic_start': 'enable',
            'match_vip': 'enable',
            'name': 'default_name_48',
            'nat': 'enable',
            'natinbound': 'enable',
            'natip': 'test_value_51',
            'natoutbound': 'enable',
            'ntlm': 'enable',
            'ntlm_guest': 'enable',
            'outbound': 'enable',
            'per_ip_shaper': 'test_value_56',
            'permit_any_host': 'enable',
            'permit_stun_host': 'enable',
            'policyid': '59',
            'profile_group': 'test_value_60',
            'profile_protocol_options': 'test_value_61',
            'profile_type': 'single',
            'radius_mac_auth_bypass': 'enable',
            'redirect_url': 'test_value_64',
            'replacemsg_override_group': 'test_value_65',
            'reputation_direction': 'source',
            'reputation_minimum': '67',
            'rsso': 'enable',
            'rtp_nat': 'disable',
            'schedule': 'test_value_70',
            'schedule_timeout': 'enable',
            'send_deny_packet': 'disable',
            'service_negate': 'enable',
            'session_ttl': '74',
            'srcaddr_negate': 'enable',
            'ssh_filter_profile': 'test_value_76',
            'ssh_policy_redirect': 'enable',
            'ssl_mirror': 'enable',
            'ssl_ssh_profile': 'test_value_79',
            'status': 'enable',
            'tcp_mss_receiver': '81',
            'tcp_mss_sender': '82',
            'tcp_session_without_syn': 'all',
            'timeout_send_rst': 'enable',
            'tos': 'test_value_85',
            'tos_mask': 'test_value_86',
            'tos_negate': 'enable',
            'traffic_shaper': 'test_value_88',
            'traffic_shaper_reverse': 'test_value_89',
            'utm_status': 'enable',
            'uuid': 'test_value_91',
            'vlan_cos_fwd': '92',
            'vlan_cos_rev': '93',
            'vlan_filter': 'test_value_94',
            'voip_profile': 'test_value_95',
            'vpntunnel': 'test_value_96',
            'waf_profile': 'test_value_97',
            'wanopt': 'enable',
            'wanopt_detection': 'active',
            'wanopt_passive_opt': 'default',
            'wanopt_peer': 'test_value_101',
            'wanopt_profile': 'test_value_102',
            'wccp': 'enable',
            'webcache': 'enable',
            'webcache_https': 'disable',
            'webfilter_profile': 'test_value_106',
            'webproxy_forward_server': 'test_value_107',
            'webproxy_profile': 'test_value_108',
            'wsso': 'enable'
        },
        'vdom': 'root'}

    is_error, changed, response = fortios_firewall_policy.fortios_firewall(input_data, fos_instance)

    expected_data = {
        'action': 'accept',
        'anti-replay': 'enable',
        'application-list': 'test_value_5',
        'auth-cert': 'test_value_6',
        'auth-path': 'enable',
        'auth-redirect-addr': 'test_value_8',
        'av-profile': 'test_value_9',
        'block-notification': 'enable',
        'captive-portal-exempt': 'enable',
        'capture-packet': 'enable',
        'cifs-profile': 'test_value_13',
        'comments': 'test_value_14',
        'delay-tcp-npu-session': 'enable',
        'diffserv-forward': 'enable',
        'diffserv-reverse': 'enable',
        'diffservcode-forward': 'test_value_18',
        'diffservcode-rev': 'test_value_19',
        'disclaimer': 'enable',
        'dlp-sensor': 'test_value_21',
        'dnsfilter-profile': 'test_value_22',
        'dsri': 'enable',
                'dstaddr-negate': 'enable',
                'email-collect': 'enable',
                'emailfilter-profile': 'test_value_26',
                'firewall-session-dirty': 'check-all',
                'fixedport': 'enable',
                'fsso': 'enable',
                'fsso-agent-for-ntlm': 'test_value_30',
                'geoip-anycast': 'enable',
                'global-label': 'test_value_32',
                'http-policy-redirect': 'enable',
                'icap-profile': 'test_value_34',
                'identity-based-route': 'test_value_35',
                'inbound': 'enable',
                'inspection-mode': 'proxy',
                'internet-service': 'enable',
                'internet-service-negate': 'enable',
                'internet-service-src': 'enable',
                'internet-service-src-negate': 'enable',
                'ippool': 'enable',
                'ips-sensor': 'test_value_43',
                'label': 'test_value_44',
                'logtraffic': 'all',
                'logtraffic-start': 'enable',
                'match-vip': 'enable',
                'name': 'default_name_48',
                'nat': 'enable',
                'natinbound': 'enable',
                'natip': 'test_value_51',
                'natoutbound': 'enable',
                'ntlm': 'enable',
                'ntlm-guest': 'enable',
                'outbound': 'enable',
                'per-ip-shaper': 'test_value_56',
                'permit-any-host': 'enable',
                'permit-stun-host': 'enable',
                'policyid': '59',
                'profile-group': 'test_value_60',
                'profile-protocol-options': 'test_value_61',
                'profile-type': 'single',
                'radius-mac-auth-bypass': 'enable',
                'redirect-url': 'test_value_64',
                'replacemsg-override-group': 'test_value_65',
                'reputation-direction': 'source',
                'reputation-minimum': '67',
                'rsso': 'enable',
                'rtp-nat': 'disable',
                'schedule': 'test_value_70',
                'schedule-timeout': 'enable',
                'send-deny-packet': 'disable',
                'service-negate': 'enable',
                'session-ttl': '74',
                'srcaddr-negate': 'enable',
                'ssh-filter-profile': 'test_value_76',
                'ssh-policy-redirect': 'enable',
                'ssl-mirror': 'enable',
                'ssl-ssh-profile': 'test_value_79',
                'status': 'enable',
                'tcp-mss-receiver': '81',
                'tcp-mss-sender': '82',
                'tcp-session-without-syn': 'all',
                'timeout-send-rst': 'enable',
                'tos': 'test_value_85',
                'tos-mask': 'test_value_86',
                'tos-negate': 'enable',
                'traffic-shaper': 'test_value_88',
                'traffic-shaper-reverse': 'test_value_89',
                'utm-status': 'enable',
                'uuid': 'test_value_91',
                'vlan-cos-fwd': '92',
                'vlan-cos-rev': '93',
                'vlan-filter': 'test_value_94',
                'voip-profile': 'test_value_95',
                'vpntunnel': 'test_value_96',
                'waf-profile': 'test_value_97',
                'wanopt': 'enable',
                'wanopt-detection': 'active',
                'wanopt-passive-opt': 'default',
                'wanopt-peer': 'test_value_101',
                'wanopt-profile': 'test_value_102',
                'wccp': 'enable',
                'webcache': 'enable',
                'webcache-https': 'disable',
                'webfilter-profile': 'test_value_106',
                'webproxy-forward-server': 'test_value_107',
                'webproxy-profile': 'test_value_108',
                'wsso': 'enable'
    }

    set_method_mock.assert_called_with('firewall', 'policy', data=expected_data, vdom='root')
    schema_method_mock.assert_not_called()
    assert not is_error
    assert changed
    assert response['status'] == 'success'
    assert response['http_status'] == 200


def test_firewall_policy_creation_fails(mocker):
    schema_method_mock = mocker.patch('ansible.module_utils.network.fortios.fortios.FortiOSHandler.schema')

    set_method_result = {'status': 'error', 'http_method': 'POST', 'http_status': 500}
    set_method_mock = mocker.patch('ansible.module_utils.network.fortios.fortios.FortiOSHandler.set', return_value=set_method_result)

    input_data = {
        'username': 'admin',
        'state': 'present',
        'firewall_policy': {
            'action': 'accept',
            'anti_replay': 'enable',
            'application_list': 'test_value_5',
            'auth_cert': 'test_value_6',
            'auth_path': 'enable',
            'auth_redirect_addr': 'test_value_8',
            'av_profile': 'test_value_9',
            'block_notification': 'enable',
            'captive_portal_exempt': 'enable',
            'capture_packet': 'enable',
            'cifs_profile': 'test_value_13',
            'comments': 'test_value_14',
            'delay_tcp_npu_session': 'enable',
            'diffserv_forward': 'enable',
            'diffserv_reverse': 'enable',
            'diffservcode_forward': 'test_value_18',
            'diffservcode_rev': 'test_value_19',
            'disclaimer': 'enable',
            'dlp_sensor': 'test_value_21',
            'dnsfilter_profile': 'test_value_22',
            'dsri': 'enable',
            'dstaddr_negate': 'enable',
            'email_collect': 'enable',
            'emailfilter_profile': 'test_value_26',
            'firewall_session_dirty': 'check-all',
            'fixedport': 'enable',
            'fsso': 'enable',
            'fsso_agent_for_ntlm': 'test_value_30',
            'geoip_anycast': 'enable',
            'global_label': 'test_value_32',
            'http_policy_redirect': 'enable',
            'icap_profile': 'test_value_34',
            'identity_based_route': 'test_value_35',
            'inbound': 'enable',
            'inspection_mode': 'proxy',
            'internet_service': 'enable',
            'internet_service_negate': 'enable',
            'internet_service_src': 'enable',
            'internet_service_src_negate': 'enable',
            'ippool': 'enable',
            'ips_sensor': 'test_value_43',
            'label': 'test_value_44',
            'logtraffic': 'all',
            'logtraffic_start': 'enable',
            'match_vip': 'enable',
            'name': 'default_name_48',
            'nat': 'enable',
            'natinbound': 'enable',
            'natip': 'test_value_51',
            'natoutbound': 'enable',
            'ntlm': 'enable',
            'ntlm_guest': 'enable',
            'outbound': 'enable',
            'per_ip_shaper': 'test_value_56',
            'permit_any_host': 'enable',
            'permit_stun_host': 'enable',
            'policyid': '59',
            'profile_group': 'test_value_60',
            'profile_protocol_options': 'test_value_61',
            'profile_type': 'single',
            'radius_mac_auth_bypass': 'enable',
            'redirect_url': 'test_value_64',
            'replacemsg_override_group': 'test_value_65',
            'reputation_direction': 'source',
            'reputation_minimum': '67',
            'rsso': 'enable',
            'rtp_nat': 'disable',
            'schedule': 'test_value_70',
            'schedule_timeout': 'enable',
            'send_deny_packet': 'disable',
            'service_negate': 'enable',
            'session_ttl': '74',
            'srcaddr_negate': 'enable',
            'ssh_filter_profile': 'test_value_76',
            'ssh_policy_redirect': 'enable',
            'ssl_mirror': 'enable',
            'ssl_ssh_profile': 'test_value_79',
            'status': 'enable',
            'tcp_mss_receiver': '81',
            'tcp_mss_sender': '82',
            'tcp_session_without_syn': 'all',
            'timeout_send_rst': 'enable',
            'tos': 'test_value_85',
            'tos_mask': 'test_value_86',
            'tos_negate': 'enable',
            'traffic_shaper': 'test_value_88',
            'traffic_shaper_reverse': 'test_value_89',
            'utm_status': 'enable',
            'uuid': 'test_value_91',
            'vlan_cos_fwd': '92',
            'vlan_cos_rev': '93',
            'vlan_filter': 'test_value_94',
            'voip_profile': 'test_value_95',
            'vpntunnel': 'test_value_96',
            'waf_profile': 'test_value_97',
            'wanopt': 'enable',
            'wanopt_detection': 'active',
            'wanopt_passive_opt': 'default',
            'wanopt_peer': 'test_value_101',
            'wanopt_profile': 'test_value_102',
            'wccp': 'enable',
            'webcache': 'enable',
            'webcache_https': 'disable',
            'webfilter_profile': 'test_value_106',
            'webproxy_forward_server': 'test_value_107',
            'webproxy_profile': 'test_value_108',
            'wsso': 'enable'
        },
        'vdom': 'root'}

    is_error, changed, response = fortios_firewall_policy.fortios_firewall(input_data, fos_instance)

    expected_data = {
        'action': 'accept',
        'anti-replay': 'enable',
        'application-list': 'test_value_5',
        'auth-cert': 'test_value_6',
        'auth-path': 'enable',
        'auth-redirect-addr': 'test_value_8',
        'av-profile': 'test_value_9',
        'block-notification': 'enable',
        'captive-portal-exempt': 'enable',
        'capture-packet': 'enable',
        'cifs-profile': 'test_value_13',
        'comments': 'test_value_14',
        'delay-tcp-npu-session': 'enable',
        'diffserv-forward': 'enable',
        'diffserv-reverse': 'enable',
        'diffservcode-forward': 'test_value_18',
        'diffservcode-rev': 'test_value_19',
        'disclaimer': 'enable',
        'dlp-sensor': 'test_value_21',
        'dnsfilter-profile': 'test_value_22',
        'dsri': 'enable',
                'dstaddr-negate': 'enable',
                'email-collect': 'enable',
                'emailfilter-profile': 'test_value_26',
                'firewall-session-dirty': 'check-all',
                'fixedport': 'enable',
                'fsso': 'enable',
                'fsso-agent-for-ntlm': 'test_value_30',
                'geoip-anycast': 'enable',
                'global-label': 'test_value_32',
                'http-policy-redirect': 'enable',
                'icap-profile': 'test_value_34',
                'identity-based-route': 'test_value_35',
                'inbound': 'enable',
                'inspection-mode': 'proxy',
                'internet-service': 'enable',
                'internet-service-negate': 'enable',
                'internet-service-src': 'enable',
                'internet-service-src-negate': 'enable',
                'ippool': 'enable',
                'ips-sensor': 'test_value_43',
                'label': 'test_value_44',
                'logtraffic': 'all',
                'logtraffic-start': 'enable',
                'match-vip': 'enable',
                'name': 'default_name_48',
                'nat': 'enable',
                'natinbound': 'enable',
                'natip': 'test_value_51',
                'natoutbound': 'enable',
                'ntlm': 'enable',
                'ntlm-guest': 'enable',
                'outbound': 'enable',
                'per-ip-shaper': 'test_value_56',
                'permit-any-host': 'enable',
                'permit-stun-host': 'enable',
                'policyid': '59',
                'profile-group': 'test_value_60',
                'profile-protocol-options': 'test_value_61',
                'profile-type': 'single',
                'radius-mac-auth-bypass': 'enable',
                'redirect-url': 'test_value_64',
                'replacemsg-override-group': 'test_value_65',
                'reputation-direction': 'source',
                'reputation-minimum': '67',
                'rsso': 'enable',
                'rtp-nat': 'disable',
                'schedule': 'test_value_70',
                'schedule-timeout': 'enable',
                'send-deny-packet': 'disable',
                'service-negate': 'enable',
                'session-ttl': '74',
                'srcaddr-negate': 'enable',
                'ssh-filter-profile': 'test_value_76',
                'ssh-policy-redirect': 'enable',
                'ssl-mirror': 'enable',
                'ssl-ssh-profile': 'test_value_79',
                'status': 'enable',
                'tcp-mss-receiver': '81',
                'tcp-mss-sender': '82',
                'tcp-session-without-syn': 'all',
                'timeout-send-rst': 'enable',
                'tos': 'test_value_85',
                'tos-mask': 'test_value_86',
                'tos-negate': 'enable',
                'traffic-shaper': 'test_value_88',
                'traffic-shaper-reverse': 'test_value_89',
                'utm-status': 'enable',
                'uuid': 'test_value_91',
                'vlan-cos-fwd': '92',
                'vlan-cos-rev': '93',
                'vlan-filter': 'test_value_94',
                'voip-profile': 'test_value_95',
                'vpntunnel': 'test_value_96',
                'waf-profile': 'test_value_97',
                'wanopt': 'enable',
                'wanopt-detection': 'active',
                'wanopt-passive-opt': 'default',
                'wanopt-peer': 'test_value_101',
                'wanopt-profile': 'test_value_102',
                'wccp': 'enable',
                'webcache': 'enable',
                'webcache-https': 'disable',
                'webfilter-profile': 'test_value_106',
                'webproxy-forward-server': 'test_value_107',
                'webproxy-profile': 'test_value_108',
                'wsso': 'enable'
    }

    set_method_mock.assert_called_with('firewall', 'policy', data=expected_data, vdom='root')
    schema_method_mock.assert_not_called()
    assert is_error
    assert not changed
    assert response['status'] == 'error'
    assert response['http_status'] == 500


def test_firewall_policy_removal(mocker):
    schema_method_mock = mocker.patch('ansible.module_utils.network.fortios.fortios.FortiOSHandler.schema')

    delete_method_result = {'status': 'success', 'http_method': 'POST', 'http_status': 200}
    delete_method_mock = mocker.patch('ansible.module_utils.network.fortios.fortios.FortiOSHandler.delete', return_value=delete_method_result)

    input_data = {
        'username': 'admin',
        'state': 'absent',
        'firewall_policy': {
            'action': 'accept',
            'anti_replay': 'enable',
            'application_list': 'test_value_5',
            'auth_cert': 'test_value_6',
            'auth_path': 'enable',
            'auth_redirect_addr': 'test_value_8',
            'av_profile': 'test_value_9',
            'block_notification': 'enable',
            'captive_portal_exempt': 'enable',
            'capture_packet': 'enable',
            'cifs_profile': 'test_value_13',
            'comments': 'test_value_14',
            'delay_tcp_npu_session': 'enable',
            'diffserv_forward': 'enable',
            'diffserv_reverse': 'enable',
            'diffservcode_forward': 'test_value_18',
            'diffservcode_rev': 'test_value_19',
            'disclaimer': 'enable',
            'dlp_sensor': 'test_value_21',
            'dnsfilter_profile': 'test_value_22',
            'dsri': 'enable',
            'dstaddr_negate': 'enable',
            'email_collect': 'enable',
            'emailfilter_profile': 'test_value_26',
            'firewall_session_dirty': 'check-all',
            'fixedport': 'enable',
            'fsso': 'enable',
            'fsso_agent_for_ntlm': 'test_value_30',
            'geoip_anycast': 'enable',
            'global_label': 'test_value_32',
            'http_policy_redirect': 'enable',
            'icap_profile': 'test_value_34',
            'identity_based_route': 'test_value_35',
            'inbound': 'enable',
            'inspection_mode': 'proxy',
            'internet_service': 'enable',
            'internet_service_negate': 'enable',
            'internet_service_src': 'enable',
            'internet_service_src_negate': 'enable',
            'ippool': 'enable',
            'ips_sensor': 'test_value_43',
            'label': 'test_value_44',
            'logtraffic': 'all',
            'logtraffic_start': 'enable',
            'match_vip': 'enable',
            'name': 'default_name_48',
            'nat': 'enable',
            'natinbound': 'enable',
            'natip': 'test_value_51',
            'natoutbound': 'enable',
            'ntlm': 'enable',
            'ntlm_guest': 'enable',
            'outbound': 'enable',
            'per_ip_shaper': 'test_value_56',
            'permit_any_host': 'enable',
            'permit_stun_host': 'enable',
            'policyid': '59',
            'profile_group': 'test_value_60',
            'profile_protocol_options': 'test_value_61',
            'profile_type': 'single',
            'radius_mac_auth_bypass': 'enable',
            'redirect_url': 'test_value_64',
            'replacemsg_override_group': 'test_value_65',
            'reputation_direction': 'source',
            'reputation_minimum': '67',
            'rsso': 'enable',
            'rtp_nat': 'disable',
            'schedule': 'test_value_70',
            'schedule_timeout': 'enable',
            'send_deny_packet': 'disable',
            'service_negate': 'enable',
            'session_ttl': '74',
            'srcaddr_negate': 'enable',
            'ssh_filter_profile': 'test_value_76',
            'ssh_policy_redirect': 'enable',
            'ssl_mirror': 'enable',
            'ssl_ssh_profile': 'test_value_79',
            'status': 'enable',
            'tcp_mss_receiver': '81',
            'tcp_mss_sender': '82',
            'tcp_session_without_syn': 'all',
            'timeout_send_rst': 'enable',
            'tos': 'test_value_85',
            'tos_mask': 'test_value_86',
            'tos_negate': 'enable',
            'traffic_shaper': 'test_value_88',
            'traffic_shaper_reverse': 'test_value_89',
            'utm_status': 'enable',
            'uuid': 'test_value_91',
            'vlan_cos_fwd': '92',
            'vlan_cos_rev': '93',
            'vlan_filter': 'test_value_94',
            'voip_profile': 'test_value_95',
            'vpntunnel': 'test_value_96',
            'waf_profile': 'test_value_97',
            'wanopt': 'enable',
            'wanopt_detection': 'active',
            'wanopt_passive_opt': 'default',
            'wanopt_peer': 'test_value_101',
            'wanopt_profile': 'test_value_102',
            'wccp': 'enable',
            'webcache': 'enable',
            'webcache_https': 'disable',
            'webfilter_profile': 'test_value_106',
            'webproxy_forward_server': 'test_value_107',
            'webproxy_profile': 'test_value_108',
            'wsso': 'enable'
        },
        'vdom': 'root'}

    is_error, changed, response = fortios_firewall_policy.fortios_firewall(input_data, fos_instance)

    delete_method_mock.assert_called_with('firewall', 'policy', mkey=ANY, vdom='root')
    schema_method_mock.assert_not_called()
    assert not is_error
    assert changed
    assert response['status'] == 'success'
    assert response['http_status'] == 200


def test_firewall_policy_deletion_fails(mocker):
    schema_method_mock = mocker.patch('ansible.module_utils.network.fortios.fortios.FortiOSHandler.schema')

    delete_method_result = {'status': 'error', 'http_method': 'POST', 'http_status': 500}
    delete_method_mock = mocker.patch('ansible.module_utils.network.fortios.fortios.FortiOSHandler.delete', return_value=delete_method_result)

    input_data = {
        'username': 'admin',
        'state': 'absent',
        'firewall_policy': {
            'action': 'accept',
            'anti_replay': 'enable',
            'application_list': 'test_value_5',
            'auth_cert': 'test_value_6',
            'auth_path': 'enable',
            'auth_redirect_addr': 'test_value_8',
            'av_profile': 'test_value_9',
            'block_notification': 'enable',
            'captive_portal_exempt': 'enable',
            'capture_packet': 'enable',
            'cifs_profile': 'test_value_13',
            'comments': 'test_value_14',
            'delay_tcp_npu_session': 'enable',
            'diffserv_forward': 'enable',
            'diffserv_reverse': 'enable',
            'diffservcode_forward': 'test_value_18',
            'diffservcode_rev': 'test_value_19',
            'disclaimer': 'enable',
            'dlp_sensor': 'test_value_21',
            'dnsfilter_profile': 'test_value_22',
            'dsri': 'enable',
            'dstaddr_negate': 'enable',
            'email_collect': 'enable',
            'emailfilter_profile': 'test_value_26',
            'firewall_session_dirty': 'check-all',
            'fixedport': 'enable',
            'fsso': 'enable',
            'fsso_agent_for_ntlm': 'test_value_30',
            'geoip_anycast': 'enable',
            'global_label': 'test_value_32',
            'http_policy_redirect': 'enable',
            'icap_profile': 'test_value_34',
            'identity_based_route': 'test_value_35',
            'inbound': 'enable',
            'inspection_mode': 'proxy',
            'internet_service': 'enable',
            'internet_service_negate': 'enable',
            'internet_service_src': 'enable',
            'internet_service_src_negate': 'enable',
            'ippool': 'enable',
            'ips_sensor': 'test_value_43',
            'label': 'test_value_44',
            'logtraffic': 'all',
            'logtraffic_start': 'enable',
            'match_vip': 'enable',
            'name': 'default_name_48',
            'nat': 'enable',
            'natinbound': 'enable',
            'natip': 'test_value_51',
            'natoutbound': 'enable',
            'ntlm': 'enable',
            'ntlm_guest': 'enable',
            'outbound': 'enable',
            'per_ip_shaper': 'test_value_56',
            'permit_any_host': 'enable',
            'permit_stun_host': 'enable',
            'policyid': '59',
            'profile_group': 'test_value_60',
            'profile_protocol_options': 'test_value_61',
            'profile_type': 'single',
            'radius_mac_auth_bypass': 'enable',
            'redirect_url': 'test_value_64',
            'replacemsg_override_group': 'test_value_65',
            'reputation_direction': 'source',
            'reputation_minimum': '67',
            'rsso': 'enable',
            'rtp_nat': 'disable',
            'schedule': 'test_value_70',
            'schedule_timeout': 'enable',
            'send_deny_packet': 'disable',
            'service_negate': 'enable',
            'session_ttl': '74',
            'srcaddr_negate': 'enable',
            'ssh_filter_profile': 'test_value_76',
            'ssh_policy_redirect': 'enable',
            'ssl_mirror': 'enable',
            'ssl_ssh_profile': 'test_value_79',
            'status': 'enable',
            'tcp_mss_receiver': '81',
            'tcp_mss_sender': '82',
            'tcp_session_without_syn': 'all',
            'timeout_send_rst': 'enable',
            'tos': 'test_value_85',
            'tos_mask': 'test_value_86',
            'tos_negate': 'enable',
            'traffic_shaper': 'test_value_88',
            'traffic_shaper_reverse': 'test_value_89',
            'utm_status': 'enable',
            'uuid': 'test_value_91',
            'vlan_cos_fwd': '92',
            'vlan_cos_rev': '93',
            'vlan_filter': 'test_value_94',
            'voip_profile': 'test_value_95',
            'vpntunnel': 'test_value_96',
            'waf_profile': 'test_value_97',
            'wanopt': 'enable',
            'wanopt_detection': 'active',
            'wanopt_passive_opt': 'default',
            'wanopt_peer': 'test_value_101',
            'wanopt_profile': 'test_value_102',
            'wccp': 'enable',
            'webcache': 'enable',
            'webcache_https': 'disable',
            'webfilter_profile': 'test_value_106',
            'webproxy_forward_server': 'test_value_107',
            'webproxy_profile': 'test_value_108',
            'wsso': 'enable'
        },
        'vdom': 'root'}

    is_error, changed, response = fortios_firewall_policy.fortios_firewall(input_data, fos_instance)

    delete_method_mock.assert_called_with('firewall', 'policy', mkey=ANY, vdom='root')
    schema_method_mock.assert_not_called()
    assert is_error
    assert not changed
    assert response['status'] == 'error'
    assert response['http_status'] == 500


def test_firewall_policy_idempotent(mocker):
    schema_method_mock = mocker.patch('ansible.module_utils.network.fortios.fortios.FortiOSHandler.schema')

    set_method_result = {'status': 'error', 'http_method': 'DELETE', 'http_status': 404}
    set_method_mock = mocker.patch('ansible.module_utils.network.fortios.fortios.FortiOSHandler.set', return_value=set_method_result)

    input_data = {
        'username': 'admin',
        'state': 'present',
        'firewall_policy': {
            'action': 'accept',
            'anti_replay': 'enable',
            'application_list': 'test_value_5',
            'auth_cert': 'test_value_6',
            'auth_path': 'enable',
            'auth_redirect_addr': 'test_value_8',
            'av_profile': 'test_value_9',
            'block_notification': 'enable',
            'captive_portal_exempt': 'enable',
            'capture_packet': 'enable',
            'cifs_profile': 'test_value_13',
            'comments': 'test_value_14',
            'delay_tcp_npu_session': 'enable',
            'diffserv_forward': 'enable',
            'diffserv_reverse': 'enable',
            'diffservcode_forward': 'test_value_18',
            'diffservcode_rev': 'test_value_19',
            'disclaimer': 'enable',
            'dlp_sensor': 'test_value_21',
            'dnsfilter_profile': 'test_value_22',
            'dsri': 'enable',
            'dstaddr_negate': 'enable',
            'email_collect': 'enable',
            'emailfilter_profile': 'test_value_26',
            'firewall_session_dirty': 'check-all',
            'fixedport': 'enable',
            'fsso': 'enable',
            'fsso_agent_for_ntlm': 'test_value_30',
            'geoip_anycast': 'enable',
            'global_label': 'test_value_32',
            'http_policy_redirect': 'enable',
            'icap_profile': 'test_value_34',
            'identity_based_route': 'test_value_35',
            'inbound': 'enable',
            'inspection_mode': 'proxy',
            'internet_service': 'enable',
            'internet_service_negate': 'enable',
            'internet_service_src': 'enable',
            'internet_service_src_negate': 'enable',
            'ippool': 'enable',
            'ips_sensor': 'test_value_43',
            'label': 'test_value_44',
            'logtraffic': 'all',
            'logtraffic_start': 'enable',
            'match_vip': 'enable',
            'name': 'default_name_48',
            'nat': 'enable',
            'natinbound': 'enable',
            'natip': 'test_value_51',
            'natoutbound': 'enable',
            'ntlm': 'enable',
            'ntlm_guest': 'enable',
            'outbound': 'enable',
            'per_ip_shaper': 'test_value_56',
            'permit_any_host': 'enable',
            'permit_stun_host': 'enable',
            'policyid': '59',
            'profile_group': 'test_value_60',
            'profile_protocol_options': 'test_value_61',
            'profile_type': 'single',
            'radius_mac_auth_bypass': 'enable',
            'redirect_url': 'test_value_64',
            'replacemsg_override_group': 'test_value_65',
            'reputation_direction': 'source',
            'reputation_minimum': '67',
            'rsso': 'enable',
            'rtp_nat': 'disable',
            'schedule': 'test_value_70',
            'schedule_timeout': 'enable',
            'send_deny_packet': 'disable',
            'service_negate': 'enable',
            'session_ttl': '74',
            'srcaddr_negate': 'enable',
            'ssh_filter_profile': 'test_value_76',
            'ssh_policy_redirect': 'enable',
            'ssl_mirror': 'enable',
            'ssl_ssh_profile': 'test_value_79',
            'status': 'enable',
            'tcp_mss_receiver': '81',
            'tcp_mss_sender': '82',
            'tcp_session_without_syn': 'all',
            'timeout_send_rst': 'enable',
            'tos': 'test_value_85',
            'tos_mask': 'test_value_86',
            'tos_negate': 'enable',
            'traffic_shaper': 'test_value_88',
            'traffic_shaper_reverse': 'test_value_89',
            'utm_status': 'enable',
            'uuid': 'test_value_91',
            'vlan_cos_fwd': '92',
            'vlan_cos_rev': '93',
            'vlan_filter': 'test_value_94',
            'voip_profile': 'test_value_95',
            'vpntunnel': 'test_value_96',
            'waf_profile': 'test_value_97',
            'wanopt': 'enable',
            'wanopt_detection': 'active',
            'wanopt_passive_opt': 'default',
            'wanopt_peer': 'test_value_101',
            'wanopt_profile': 'test_value_102',
            'wccp': 'enable',
            'webcache': 'enable',
            'webcache_https': 'disable',
            'webfilter_profile': 'test_value_106',
            'webproxy_forward_server': 'test_value_107',
            'webproxy_profile': 'test_value_108',
            'wsso': 'enable'
        },
        'vdom': 'root'}

    is_error, changed, response = fortios_firewall_policy.fortios_firewall(input_data, fos_instance)

    expected_data = {
        'action': 'accept',
        'anti-replay': 'enable',
        'application-list': 'test_value_5',
        'auth-cert': 'test_value_6',
        'auth-path': 'enable',
        'auth-redirect-addr': 'test_value_8',
        'av-profile': 'test_value_9',
        'block-notification': 'enable',
        'captive-portal-exempt': 'enable',
        'capture-packet': 'enable',
        'cifs-profile': 'test_value_13',
        'comments': 'test_value_14',
        'delay-tcp-npu-session': 'enable',
        'diffserv-forward': 'enable',
        'diffserv-reverse': 'enable',
        'diffservcode-forward': 'test_value_18',
        'diffservcode-rev': 'test_value_19',
        'disclaimer': 'enable',
        'dlp-sensor': 'test_value_21',
        'dnsfilter-profile': 'test_value_22',
        'dsri': 'enable',
                'dstaddr-negate': 'enable',
                'email-collect': 'enable',
                'emailfilter-profile': 'test_value_26',
                'firewall-session-dirty': 'check-all',
                'fixedport': 'enable',
                'fsso': 'enable',
                'fsso-agent-for-ntlm': 'test_value_30',
                'geoip-anycast': 'enable',
                'global-label': 'test_value_32',
                'http-policy-redirect': 'enable',
                'icap-profile': 'test_value_34',
                'identity-based-route': 'test_value_35',
                'inbound': 'enable',
                'inspection-mode': 'proxy',
                'internet-service': 'enable',
                'internet-service-negate': 'enable',
                'internet-service-src': 'enable',
                'internet-service-src-negate': 'enable',
                'ippool': 'enable',
                'ips-sensor': 'test_value_43',
                'label': 'test_value_44',
                'logtraffic': 'all',
                'logtraffic-start': 'enable',
                'match-vip': 'enable',
                'name': 'default_name_48',
                'nat': 'enable',
                'natinbound': 'enable',
                'natip': 'test_value_51',
                'natoutbound': 'enable',
                'ntlm': 'enable',
                'ntlm-guest': 'enable',
                'outbound': 'enable',
                'per-ip-shaper': 'test_value_56',
                'permit-any-host': 'enable',
                'permit-stun-host': 'enable',
                'policyid': '59',
                'profile-group': 'test_value_60',
                'profile-protocol-options': 'test_value_61',
                'profile-type': 'single',
                'radius-mac-auth-bypass': 'enable',
                'redirect-url': 'test_value_64',
                'replacemsg-override-group': 'test_value_65',
                'reputation-direction': 'source',
                'reputation-minimum': '67',
                'rsso': 'enable',
                'rtp-nat': 'disable',
                'schedule': 'test_value_70',
                'schedule-timeout': 'enable',
                'send-deny-packet': 'disable',
                'service-negate': 'enable',
                'session-ttl': '74',
                'srcaddr-negate': 'enable',
                'ssh-filter-profile': 'test_value_76',
                'ssh-policy-redirect': 'enable',
                'ssl-mirror': 'enable',
                'ssl-ssh-profile': 'test_value_79',
                'status': 'enable',
                'tcp-mss-receiver': '81',
                'tcp-mss-sender': '82',
                'tcp-session-without-syn': 'all',
                'timeout-send-rst': 'enable',
                'tos': 'test_value_85',
                'tos-mask': 'test_value_86',
                'tos-negate': 'enable',
                'traffic-shaper': 'test_value_88',
                'traffic-shaper-reverse': 'test_value_89',
                'utm-status': 'enable',
                'uuid': 'test_value_91',
                'vlan-cos-fwd': '92',
                'vlan-cos-rev': '93',
                'vlan-filter': 'test_value_94',
                'voip-profile': 'test_value_95',
                'vpntunnel': 'test_value_96',
                'waf-profile': 'test_value_97',
                'wanopt': 'enable',
                'wanopt-detection': 'active',
                'wanopt-passive-opt': 'default',
                'wanopt-peer': 'test_value_101',
                'wanopt-profile': 'test_value_102',
                'wccp': 'enable',
                'webcache': 'enable',
                'webcache-https': 'disable',
                'webfilter-profile': 'test_value_106',
                'webproxy-forward-server': 'test_value_107',
                'webproxy-profile': 'test_value_108',
                'wsso': 'enable'
    }

    set_method_mock.assert_called_with('firewall', 'policy', data=expected_data, vdom='root')
    schema_method_mock.assert_not_called()
    assert not is_error
    assert not changed
    assert response['status'] == 'error'
    assert response['http_status'] == 404


def test_firewall_policy_filter_foreign_attributes(mocker):
    schema_method_mock = mocker.patch('ansible.module_utils.network.fortios.fortios.FortiOSHandler.schema')

    set_method_result = {'status': 'success', 'http_method': 'POST', 'http_status': 200}
    set_method_mock = mocker.patch('ansible.module_utils.network.fortios.fortios.FortiOSHandler.set', return_value=set_method_result)

    input_data = {
        'username': 'admin',
        'state': 'present',
        'firewall_policy': {
            'random_attribute_not_valid': 'tag',
            'action': 'accept',
            'anti_replay': 'enable',
            'application_list': 'test_value_5',
            'auth_cert': 'test_value_6',
            'auth_path': 'enable',
            'auth_redirect_addr': 'test_value_8',
            'av_profile': 'test_value_9',
            'block_notification': 'enable',
            'captive_portal_exempt': 'enable',
            'capture_packet': 'enable',
            'cifs_profile': 'test_value_13',
            'comments': 'test_value_14',
            'delay_tcp_npu_session': 'enable',
            'diffserv_forward': 'enable',
            'diffserv_reverse': 'enable',
            'diffservcode_forward': 'test_value_18',
            'diffservcode_rev': 'test_value_19',
            'disclaimer': 'enable',
            'dlp_sensor': 'test_value_21',
            'dnsfilter_profile': 'test_value_22',
            'dsri': 'enable',
            'dstaddr_negate': 'enable',
            'email_collect': 'enable',
            'emailfilter_profile': 'test_value_26',
            'firewall_session_dirty': 'check-all',
            'fixedport': 'enable',
            'fsso': 'enable',
            'fsso_agent_for_ntlm': 'test_value_30',
            'geoip_anycast': 'enable',
            'global_label': 'test_value_32',
            'http_policy_redirect': 'enable',
            'icap_profile': 'test_value_34',
            'identity_based_route': 'test_value_35',
            'inbound': 'enable',
            'inspection_mode': 'proxy',
            'internet_service': 'enable',
            'internet_service_negate': 'enable',
            'internet_service_src': 'enable',
            'internet_service_src_negate': 'enable',
            'ippool': 'enable',
            'ips_sensor': 'test_value_43',
            'label': 'test_value_44',
            'logtraffic': 'all',
            'logtraffic_start': 'enable',
            'match_vip': 'enable',
            'name': 'default_name_48',
            'nat': 'enable',
            'natinbound': 'enable',
            'natip': 'test_value_51',
            'natoutbound': 'enable',
            'ntlm': 'enable',
            'ntlm_guest': 'enable',
            'outbound': 'enable',
            'per_ip_shaper': 'test_value_56',
            'permit_any_host': 'enable',
            'permit_stun_host': 'enable',
            'policyid': '59',
            'profile_group': 'test_value_60',
            'profile_protocol_options': 'test_value_61',
            'profile_type': 'single',
            'radius_mac_auth_bypass': 'enable',
            'redirect_url': 'test_value_64',
            'replacemsg_override_group': 'test_value_65',
            'reputation_direction': 'source',
            'reputation_minimum': '67',
            'rsso': 'enable',
            'rtp_nat': 'disable',
            'schedule': 'test_value_70',
            'schedule_timeout': 'enable',
            'send_deny_packet': 'disable',
            'service_negate': 'enable',
            'session_ttl': '74',
            'srcaddr_negate': 'enable',
            'ssh_filter_profile': 'test_value_76',
            'ssh_policy_redirect': 'enable',
            'ssl_mirror': 'enable',
            'ssl_ssh_profile': 'test_value_79',
            'status': 'enable',
            'tcp_mss_receiver': '81',
            'tcp_mss_sender': '82',
            'tcp_session_without_syn': 'all',
            'timeout_send_rst': 'enable',
            'tos': 'test_value_85',
            'tos_mask': 'test_value_86',
            'tos_negate': 'enable',
            'traffic_shaper': 'test_value_88',
            'traffic_shaper_reverse': 'test_value_89',
            'utm_status': 'enable',
            'uuid': 'test_value_91',
            'vlan_cos_fwd': '92',
            'vlan_cos_rev': '93',
            'vlan_filter': 'test_value_94',
            'voip_profile': 'test_value_95',
            'vpntunnel': 'test_value_96',
            'waf_profile': 'test_value_97',
            'wanopt': 'enable',
            'wanopt_detection': 'active',
            'wanopt_passive_opt': 'default',
            'wanopt_peer': 'test_value_101',
            'wanopt_profile': 'test_value_102',
            'wccp': 'enable',
            'webcache': 'enable',
            'webcache_https': 'disable',
            'webfilter_profile': 'test_value_106',
            'webproxy_forward_server': 'test_value_107',
            'webproxy_profile': 'test_value_108',
            'wsso': 'enable'
        },
        'vdom': 'root'}

    is_error, changed, response = fortios_firewall_policy.fortios_firewall(input_data, fos_instance)

    expected_data = {
        'action': 'accept',
        'anti-replay': 'enable',
        'application-list': 'test_value_5',
        'auth-cert': 'test_value_6',
        'auth-path': 'enable',
        'auth-redirect-addr': 'test_value_8',
        'av-profile': 'test_value_9',
        'block-notification': 'enable',
        'captive-portal-exempt': 'enable',
        'capture-packet': 'enable',
        'cifs-profile': 'test_value_13',
        'comments': 'test_value_14',
        'delay-tcp-npu-session': 'enable',
        'diffserv-forward': 'enable',
        'diffserv-reverse': 'enable',
        'diffservcode-forward': 'test_value_18',
        'diffservcode-rev': 'test_value_19',
        'disclaimer': 'enable',
        'dlp-sensor': 'test_value_21',
        'dnsfilter-profile': 'test_value_22',
        'dsri': 'enable',
                'dstaddr-negate': 'enable',
                'email-collect': 'enable',
                'emailfilter-profile': 'test_value_26',
                'firewall-session-dirty': 'check-all',
                'fixedport': 'enable',
                'fsso': 'enable',
                'fsso-agent-for-ntlm': 'test_value_30',
                'geoip-anycast': 'enable',
                'global-label': 'test_value_32',
                'http-policy-redirect': 'enable',
                'icap-profile': 'test_value_34',
                'identity-based-route': 'test_value_35',
                'inbound': 'enable',
                'inspection-mode': 'proxy',
                'internet-service': 'enable',
                'internet-service-negate': 'enable',
                'internet-service-src': 'enable',
                'internet-service-src-negate': 'enable',
                'ippool': 'enable',
                'ips-sensor': 'test_value_43',
                'label': 'test_value_44',
                'logtraffic': 'all',
                'logtraffic-start': 'enable',
                'match-vip': 'enable',
                'name': 'default_name_48',
                'nat': 'enable',
                'natinbound': 'enable',
                'natip': 'test_value_51',
                'natoutbound': 'enable',
                'ntlm': 'enable',
                'ntlm-guest': 'enable',
                'outbound': 'enable',
                'per-ip-shaper': 'test_value_56',
                'permit-any-host': 'enable',
                'permit-stun-host': 'enable',
                'policyid': '59',
                'profile-group': 'test_value_60',
                'profile-protocol-options': 'test_value_61',
                'profile-type': 'single',
                'radius-mac-auth-bypass': 'enable',
                'redirect-url': 'test_value_64',
                'replacemsg-override-group': 'test_value_65',
                'reputation-direction': 'source',
                'reputation-minimum': '67',
                'rsso': 'enable',
                'rtp-nat': 'disable',
                'schedule': 'test_value_70',
                'schedule-timeout': 'enable',
                'send-deny-packet': 'disable',
                'service-negate': 'enable',
                'session-ttl': '74',
                'srcaddr-negate': 'enable',
                'ssh-filter-profile': 'test_value_76',
                'ssh-policy-redirect': 'enable',
                'ssl-mirror': 'enable',
                'ssl-ssh-profile': 'test_value_79',
                'status': 'enable',
                'tcp-mss-receiver': '81',
                'tcp-mss-sender': '82',
                'tcp-session-without-syn': 'all',
                'timeout-send-rst': 'enable',
                'tos': 'test_value_85',
                'tos-mask': 'test_value_86',
                'tos-negate': 'enable',
                'traffic-shaper': 'test_value_88',
                'traffic-shaper-reverse': 'test_value_89',
                'utm-status': 'enable',
                'uuid': 'test_value_91',
                'vlan-cos-fwd': '92',
                'vlan-cos-rev': '93',
                'vlan-filter': 'test_value_94',
                'voip-profile': 'test_value_95',
                'vpntunnel': 'test_value_96',
                'waf-profile': 'test_value_97',
                'wanopt': 'enable',
                'wanopt-detection': 'active',
                'wanopt-passive-opt': 'default',
                'wanopt-peer': 'test_value_101',
                'wanopt-profile': 'test_value_102',
                'wccp': 'enable',
                'webcache': 'enable',
                'webcache-https': 'disable',
                'webfilter-profile': 'test_value_106',
                'webproxy-forward-server': 'test_value_107',
                'webproxy-profile': 'test_value_108',
                'wsso': 'enable'
    }

    set_method_mock.assert_called_with('firewall', 'policy', data=expected_data, vdom='root')
    schema_method_mock.assert_not_called()
    assert not is_error
    assert changed
    assert response['status'] == 'success'
    assert response['http_status'] == 200
