- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
   ssl_verify: "False"
  tasks:
  - name: Configure ICAP profiles.
    fortios_icap_profile:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      state: "present"
      icap_profile:
        icap_headers:
         -
            base64_encoding: "disable"
            content: "<your_own_value>"
            id:  "6"
            name: "default_name_7"
        methods: "delete"
        name: "default_name_9"
        preview: "disable"
        preview_data_length: "11"
        replacemsg_group: "<your_own_value> (source system.replacemsg-group.name)"
        request: "disable"
        request_failure: "error"
        request_path: "<your_own_value>"
        request_server: "<your_own_value> (source icap.server.name)"
        response: "disable"
        response_failure: "error"
        response_path: "<your_own_value>"
        response_req_hdr: "disable"
        response_server: "<your_own_value> (source icap.server.name)"
        streaming_content_bypass: "disable"
