- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
   ssl_verify: "False"
  tasks:
  - name: Configure system NTP information.
    fortios_system_ntp:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      system_ntp:
        authentication: "enable"
        interface:
         -
            interface_name: "<your_own_value> (source system.interface.name)"
        key: "<your_own_value>"
        key_id: "7"
        key_type: "MD5"
        ntpserver:
         -
            authentication: "enable"
            id:  "11"
            key: "<your_own_value>"
            key_id: "13"
            ntpv3: "enable"
            server: "192.168.100.40"
        ntpsync: "enable"
        server_mode: "enable"
        source_ip: "84.230.14.43"
        source_ip6: "<your_own_value>"
        syncinterval: "20"
        type: "fortiguard"
